### PR TITLE
feature: Add SwitchComponent to toggle dark mode into SettingsComponent.

### PR DESCRIPTION
**Pull request by rbinsztock**
- Added SwitchComponent in SettingsComponent to switch light/dark mode for documentation.
- Added dark.css for dark mode.

Verified on Chrome, Firefox & Edge.

Thank you

### CODE REVIEW

**Comment by aslushnikov** [comment]
Thank you for the PR! This is awesome.

Some feedback to make it even more awesome:
- can we put the dark theme toggle in the settings? (settings open if you click on the pptr version)
- settings doesn't respect dark mode :'(

image

- the sidebar selection doesn't respect dark mode

image

- external link icon has white background. It's an SVG - can we make it black inside?

image

**Comment by rbinsztock** [comment]
Hi and thank you for the review.

I moved the switch into settings, fixed all missing elements already not in dark.

Now I have a little problem to activate the checkbox on reload. The checkbox is not anymore always in the DOM so I need an Observable to check if element is here to activate it or check the value when opening settingsComponent maybe ?

I will check tomorrow how to do it.

**Comment by rbinsztock** [comment]
Is it now mergeable @aslushnikov ?

**Comment by rbinsztock** [comment]
Hi @aslushnikov, can you look at it again please ?

**Comment by aslushnikov** [comment]
cc @mathiasbynens

**Comment by rbinsztock** [comment]
I can reopen it if you want it.

**Pull request closed without merging**
